"""Pydantic schemas for Interview Agent."""
from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal, Optional, List


class InterviewQuestion(BaseModel):
    """A single interview question generated by the agent."""
    question: str = Field(..., description="The interview question text in Persian")
    difficulty: str = Field(..., description="Difficulty level: easy/medium/hard")
    rationale: str = Field(..., description="Why this question was asked based on job requirements")
    competency: str = Field(..., description="Exact job-related competency being assessed")
    purpose: str = Field(..., description="User-facing purpose of this question")
    assessment_criteria: List[str] = Field(default_factory=list)


class CriterionEvaluation(BaseModel):
    criterion: str
    score: int | None = Field(default=None, ge=1, le=5)
    explanation: str
    evidence: List[str] = Field(default_factory=list)
    weight: float = Field(default=1.0, ge=0)
    required: bool = True


class InterviewFeedback(BaseModel):
    """Feedback on the user's answer to a question."""
    feedback: str = Field(..., description="Specific feedback on the answer in Persian")
    strengths: List[str] = Field(default_factory=list, description="What the user did well")
    weaknesses: List[str] = Field(default_factory=list, description="Areas for improvement")
    better_answer_hint: str = Field(..., description="A hint for a better answer")
    criteria: List[CriterionEvaluation] = Field(default_factory=list)
    overall_score: int | None = Field(default=None, ge=1, le=5)
    insufficient_evidence: bool = True
    improvement_suggestions: List[str] = Field(default_factory=list)
    follow_up_question: str | None = None
    evaluation_version: str = "interview-rubric/1"


class InterviewSummary(BaseModel):
    """Final summary after completing all questions."""
    overall_feedback: str = Field(..., description="Overall assessment in Persian")
    topics_to_study: List[str] = Field(default_factory=list, description="Recommended topics to study")
    competencies_covered: List[str] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)
    areas_needing_evidence: List[str] = Field(default_factory=list)
    next_steps: List[str] = Field(default_factory=list)
    evaluation_version: str = "interview-rubric/1"


class InterviewGenerateQuestionRequest(BaseModel):
    """Request to generate the next interview question."""
    job_analysis: dict = Field(..., description="JobAnalysis data from Stage 1")
    career_snapshot: dict = Field(..., description="CareerMemorySnapshot of the user")
    persona: str = Field(default="مدیر فنی سخت‌گیر", description="Interviewer persona")
    question_number: int = Field(default=1, description="Current question number (1-indexed)")
    max_questions: int = Field(default=3, description="Total number of questions in this session")
    previous_answers: List[dict] = Field(default_factory=list, description="Previous Q&A pairs")
    interview_type: Literal["technical", "behavioral", "general"] = "technical"
    available_competencies: List[str] = Field(default_factory=list)
    previous_questions: List[str] = Field(default_factory=list)
    previous_evaluations: List[dict] = Field(default_factory=list)


class InterviewGenerateQuestionResponse(BaseModel):
    """Response with a new interview question."""
    question: InterviewQuestion
    is_final: bool = Field(default=False, description="True if this is the last question")


class InterviewProcessAnswerRequest(BaseModel):
    """Request to process user's answer and provide feedback."""
    job_analysis: dict = Field(..., description="JobAnalysis data from Stage 1")
    career_snapshot: dict = Field(..., description="CareerMemorySnapshot of the user")
    persona: str = Field(default="مدیر فنی سخت‌گیر", description="Interviewer persona")
    question: str = Field(..., description="The question that was asked")
    answer: str = Field(..., description="The user's answer")
    question_number: int = Field(default=1, description="Current question number (1-indexed)")
    max_questions: int = Field(default=3, description="Total number of questions in this session")
    previous_answers: List[dict] = Field(default_factory=list, description="Previous Q&A pairs")
    interview_type: Literal["technical", "behavioral", "general"] = "technical"
    competency: str = ""
    assessment_criteria: List[str] = Field(default_factory=list)
    previous_evaluations: List[dict] = Field(default_factory=list)
    available_competencies: List[str] = Field(default_factory=list)


class InterviewProcessAnswerResponse(BaseModel):
    """Response with feedback and optionally the next question."""
    feedback: InterviewFeedback
    next_question: Optional[InterviewQuestion] = Field(default=None, description="Next question if not done")
    is_complete: bool = Field(default=False, description="True if interview is complete")
    summary: Optional[InterviewSummary] = Field(default=None, description="Final summary if complete")
