# Generated by Django 6.1.1 on 2026-10-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(default="رزومهٔ من", max_length=160)),
                ("content", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رزومه",
                "verbose_name_plural": "رزومه\u200cها",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ResumeFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازخورد رزومه",
                "verbose_name_plural": "بازخوردهای رزومه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="resume",
            constraint=models.UniqueConstraint(
                fields=("user", "version"), name="uniq_resume_version_per_user"
            ),
        ),
    ]
