# Generated by Django 6.1.1 on 2026-10-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "کاربر"),
                            ("assistant", "ایجنت"),
                            ("system", "سیستم"),
                        ],
                        max_length=12,
                    ),
                ),
                ("content", models.TextField()),
                ("tool_name", models.CharField(blank=True, max_length=40)),
                ("tool_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام چت",
                "verbose_name_plural": "پیام\u200cهای چت",
                "ordering": ["created_at"],
            },
        ),
    ]
