# Generated by Django 5.2.6 on 2026-10-09 21:57

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_sessions_legacy(apps, schema_editor):
    InterviewSession = apps.get_model("interview", "InterviewSession")
    InterviewSession.objects.using(schema_editor.connection.alias).update(
        rubric_version="interview-legacy/0"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("general", "General"),
                ],
                default="technical",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="job_posting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_sessions",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="max_questions",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="rubric_version",
            field=models.CharField(default="interview-rubric/1", max_length=32),
        ),
        migrations.RunPython(
            mark_existing_sessions_legacy,
            migrations.RunPython.noop,
        ),
    ]
