# Generated by Django 5.2.6 on 2026-10-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_memory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="memoryevidence",
            new_name="career_memo_memory__6c3aa2_idx",
            old_name="cm_evidence_memory_content_idx",
        ),
        migrations.AlterField(
            model_name="skill",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("needs_clarification", "Needs clarification"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("pending_confirmation", "Pending confirmation"),
                ],
                default="unverified",
                max_length=30,
            ),
        ),
    ]
