# Generated by Django 5.2.6 on 2026-10-08 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_analysis",
                    models.JSONField(help_text="JobAnalysis snapshot from Stage 1"),
                ),
                (
                    "persona",
                    models.CharField(
                        default="مدیر فنی سخت\u200cگیر",
                        help_text="Interviewer persona",
                        max_length=100,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(default=list, help_text="List of questions asked"),
                ),
                (
                    "answers",
                    models.JSONField(default=list, help_text="List of user answers"),
                ),
                (
                    "feedback_history",
                    models.JSONField(
                        default=list, help_text="List of feedback for each answer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True, help_text="Final interview summary", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه مصاحبه",
                "verbose_name_plural": "جلسات مصاحبه",
                "ordering": ["-created_at"],
            },
        ),
    ]
