# Generated by Django 6.1.1 on 2026-10-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("level", models.CharField(blank=True, max_length=16)),
                ("required_skills", models.JSONField(default=list)),
                ("optional_skills", models.JSONField(blank=True, default=list)),
                ("job_types", models.JSONField(blank=True, default=list)),
                ("salary_min", models.IntegerField(blank=True, null=True)),
                ("salary_max", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=400)),
                (
                    "source",
                    models.CharField(
                        choices=[("seed", "داده اولیه"), ("scrape", "اسکرپ")],
                        default="seed",
                        max_length=10,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "آگهی شغلی",
                "verbose_name_plural": "آگهی\u200cهای شغلی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("saved", "ذخیره"),
                            ("dismissed", "ردشده"),
                            ("applied", "درخواست داده"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تناسب آگهی",
                "verbose_name_plural": "تناسب آگهی\u200cها",
                "ordering": ["-score"],
                "unique_together": {("user", "job")},
            },
        ),
    ]
