# Generated by Django 6.1.1 on 2026-10-05 19:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نام و نام خانوادگی"
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="تیتر حرفه\u200cای"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="مهارت\u200cها"
                    ),
                ),
                (
                    "experience_years",
                    models.FloatField(default=0, verbose_name="سال تجربه"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intern", "کارآموز"),
                            ("junior", "جونیور"),
                            ("mid", "میان\u200cرده"),
                            ("senior", "ارشد"),
                        ],
                        default="junior",
                        max_length=16,
                        verbose_name="سطح",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="نقش هدف"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                (
                    "remote_only",
                    models.BooleanField(default=False, verbose_name="فقط دورکاری"),
                ),
                (
                    "preferred_job_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="نوع همکاری"
                    ),
                ),
                (
                    "min_salary",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="حداقل حقوق (تومان)"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="تحصیلات"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True, default=list, verbose_name="زبان\u200cها"
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="لینک\u200cها"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="تکمیل\u200cشده"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
